//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChitApplication.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Details", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Details : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int registrationnumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string firstnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lastnameField;
        
        private int phonenumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string addressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string chitidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string paiddateField;
        
        private int amountpaidField;
        
        private int paymentidField;
        
        private int eminoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int registrationnumber {
            get {
                return this.registrationnumberField;
            }
            set {
                if ((this.registrationnumberField.Equals(value) != true)) {
                    this.registrationnumberField = value;
                    this.RaisePropertyChanged("registrationnumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string firstname {
            get {
                return this.firstnameField;
            }
            set {
                if ((object.ReferenceEquals(this.firstnameField, value) != true)) {
                    this.firstnameField = value;
                    this.RaisePropertyChanged("firstname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string lastname {
            get {
                return this.lastnameField;
            }
            set {
                if ((object.ReferenceEquals(this.lastnameField, value) != true)) {
                    this.lastnameField = value;
                    this.RaisePropertyChanged("lastname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int phonenumber {
            get {
                return this.phonenumberField;
            }
            set {
                if ((this.phonenumberField.Equals(value) != true)) {
                    this.phonenumberField = value;
                    this.RaisePropertyChanged("phonenumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string address {
            get {
                return this.addressField;
            }
            set {
                if ((object.ReferenceEquals(this.addressField, value) != true)) {
                    this.addressField = value;
                    this.RaisePropertyChanged("address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string chitid {
            get {
                return this.chitidField;
            }
            set {
                if ((object.ReferenceEquals(this.chitidField, value) != true)) {
                    this.chitidField = value;
                    this.RaisePropertyChanged("chitid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string paiddate {
            get {
                return this.paiddateField;
            }
            set {
                if ((object.ReferenceEquals(this.paiddateField, value) != true)) {
                    this.paiddateField = value;
                    this.RaisePropertyChanged("paiddate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int amountpaid {
            get {
                return this.amountpaidField;
            }
            set {
                if ((this.amountpaidField.Equals(value) != true)) {
                    this.amountpaidField = value;
                    this.RaisePropertyChanged("amountpaid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public int paymentid {
            get {
                return this.paymentidField;
            }
            set {
                if ((this.paymentidField.Equals(value) != true)) {
                    this.paymentidField = value;
                    this.RaisePropertyChanged("paymentid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public int emino {
            get {
                return this.eminoField;
            }
            set {
                if ((this.eminoField.Equals(value) != true)) {
                    this.eminoField = value;
                    this.RaisePropertyChanged("emino");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.ChitApplicationServiceSoap")]
    public interface ChitApplicationServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        ChitApplication.ServiceReference.HelloWorldResponse HelloWorld(ChitApplication.ServiceReference.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<ChitApplication.ServiceReference.HelloWorldResponse> HelloWorldAsync(ChitApplication.ServiceReference.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name values from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertRegistration", ReplyAction="*")]
        ChitApplication.ServiceReference.InsertRegistrationResponse InsertRegistration(ChitApplication.ServiceReference.InsertRegistrationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertRegistration", ReplyAction="*")]
        System.Threading.Tasks.Task<ChitApplication.ServiceReference.InsertRegistrationResponse> InsertRegistrationAsync(ChitApplication.ServiceReference.InsertRegistrationRequest request);
        
        // CODEGEN: Generating message contract since element name values from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertPaymentDetails", ReplyAction="*")]
        ChitApplication.ServiceReference.InsertPaymentDetailsResponse InsertPaymentDetails(ChitApplication.ServiceReference.InsertPaymentDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertPaymentDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<ChitApplication.ServiceReference.InsertPaymentDetailsResponse> InsertPaymentDetailsAsync(ChitApplication.ServiceReference.InsertPaymentDetailsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public ChitApplication.ServiceReference.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(ChitApplication.ServiceReference.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public ChitApplication.ServiceReference.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(ChitApplication.ServiceReference.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertRegistrationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertRegistration", Namespace="http://tempuri.org/", Order=0)]
        public ChitApplication.ServiceReference.InsertRegistrationRequestBody Body;
        
        public InsertRegistrationRequest() {
        }
        
        public InsertRegistrationRequest(ChitApplication.ServiceReference.InsertRegistrationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertRegistrationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ChitApplication.ServiceReference.Details values;
        
        public InsertRegistrationRequestBody() {
        }
        
        public InsertRegistrationRequestBody(ChitApplication.ServiceReference.Details values) {
            this.values = values;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertRegistrationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertRegistrationResponse", Namespace="http://tempuri.org/", Order=0)]
        public ChitApplication.ServiceReference.InsertRegistrationResponseBody Body;
        
        public InsertRegistrationResponse() {
        }
        
        public InsertRegistrationResponse(ChitApplication.ServiceReference.InsertRegistrationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertRegistrationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool InsertRegistrationResult;
        
        public InsertRegistrationResponseBody() {
        }
        
        public InsertRegistrationResponseBody(bool InsertRegistrationResult) {
            this.InsertRegistrationResult = InsertRegistrationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertPaymentDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertPaymentDetails", Namespace="http://tempuri.org/", Order=0)]
        public ChitApplication.ServiceReference.InsertPaymentDetailsRequestBody Body;
        
        public InsertPaymentDetailsRequest() {
        }
        
        public InsertPaymentDetailsRequest(ChitApplication.ServiceReference.InsertPaymentDetailsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertPaymentDetailsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ChitApplication.ServiceReference.Details values;
        
        public InsertPaymentDetailsRequestBody() {
        }
        
        public InsertPaymentDetailsRequestBody(ChitApplication.ServiceReference.Details values) {
            this.values = values;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertPaymentDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertPaymentDetailsResponse", Namespace="http://tempuri.org/", Order=0)]
        public ChitApplication.ServiceReference.InsertPaymentDetailsResponseBody Body;
        
        public InsertPaymentDetailsResponse() {
        }
        
        public InsertPaymentDetailsResponse(ChitApplication.ServiceReference.InsertPaymentDetailsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertPaymentDetailsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool InsertPaymentDetailsResult;
        
        public InsertPaymentDetailsResponseBody() {
        }
        
        public InsertPaymentDetailsResponseBody(bool InsertPaymentDetailsResult) {
            this.InsertPaymentDetailsResult = InsertPaymentDetailsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ChitApplicationServiceSoapChannel : ChitApplication.ServiceReference.ChitApplicationServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ChitApplicationServiceSoapClient : System.ServiceModel.ClientBase<ChitApplication.ServiceReference.ChitApplicationServiceSoap>, ChitApplication.ServiceReference.ChitApplicationServiceSoap {
        
        public ChitApplicationServiceSoapClient() {
        }
        
        public ChitApplicationServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ChitApplicationServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChitApplicationServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChitApplicationServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ChitApplication.ServiceReference.HelloWorldResponse ChitApplication.ServiceReference.ChitApplicationServiceSoap.HelloWorld(ChitApplication.ServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            ChitApplication.ServiceReference.HelloWorldRequest inValue = new ChitApplication.ServiceReference.HelloWorldRequest();
            inValue.Body = new ChitApplication.ServiceReference.HelloWorldRequestBody();
            ChitApplication.ServiceReference.HelloWorldResponse retVal = ((ChitApplication.ServiceReference.ChitApplicationServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ChitApplication.ServiceReference.HelloWorldResponse> ChitApplication.ServiceReference.ChitApplicationServiceSoap.HelloWorldAsync(ChitApplication.ServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<ChitApplication.ServiceReference.HelloWorldResponse> HelloWorldAsync() {
            ChitApplication.ServiceReference.HelloWorldRequest inValue = new ChitApplication.ServiceReference.HelloWorldRequest();
            inValue.Body = new ChitApplication.ServiceReference.HelloWorldRequestBody();
            return ((ChitApplication.ServiceReference.ChitApplicationServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ChitApplication.ServiceReference.InsertRegistrationResponse ChitApplication.ServiceReference.ChitApplicationServiceSoap.InsertRegistration(ChitApplication.ServiceReference.InsertRegistrationRequest request) {
            return base.Channel.InsertRegistration(request);
        }
        
        public bool InsertRegistration(ChitApplication.ServiceReference.Details values) {
            ChitApplication.ServiceReference.InsertRegistrationRequest inValue = new ChitApplication.ServiceReference.InsertRegistrationRequest();
            inValue.Body = new ChitApplication.ServiceReference.InsertRegistrationRequestBody();
            inValue.Body.values = values;
            ChitApplication.ServiceReference.InsertRegistrationResponse retVal = ((ChitApplication.ServiceReference.ChitApplicationServiceSoap)(this)).InsertRegistration(inValue);
            return retVal.Body.InsertRegistrationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ChitApplication.ServiceReference.InsertRegistrationResponse> ChitApplication.ServiceReference.ChitApplicationServiceSoap.InsertRegistrationAsync(ChitApplication.ServiceReference.InsertRegistrationRequest request) {
            return base.Channel.InsertRegistrationAsync(request);
        }
        
        public System.Threading.Tasks.Task<ChitApplication.ServiceReference.InsertRegistrationResponse> InsertRegistrationAsync(ChitApplication.ServiceReference.Details values) {
            ChitApplication.ServiceReference.InsertRegistrationRequest inValue = new ChitApplication.ServiceReference.InsertRegistrationRequest();
            inValue.Body = new ChitApplication.ServiceReference.InsertRegistrationRequestBody();
            inValue.Body.values = values;
            return ((ChitApplication.ServiceReference.ChitApplicationServiceSoap)(this)).InsertRegistrationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ChitApplication.ServiceReference.InsertPaymentDetailsResponse ChitApplication.ServiceReference.ChitApplicationServiceSoap.InsertPaymentDetails(ChitApplication.ServiceReference.InsertPaymentDetailsRequest request) {
            return base.Channel.InsertPaymentDetails(request);
        }
        
        public bool InsertPaymentDetails(ChitApplication.ServiceReference.Details values) {
            ChitApplication.ServiceReference.InsertPaymentDetailsRequest inValue = new ChitApplication.ServiceReference.InsertPaymentDetailsRequest();
            inValue.Body = new ChitApplication.ServiceReference.InsertPaymentDetailsRequestBody();
            inValue.Body.values = values;
            ChitApplication.ServiceReference.InsertPaymentDetailsResponse retVal = ((ChitApplication.ServiceReference.ChitApplicationServiceSoap)(this)).InsertPaymentDetails(inValue);
            return retVal.Body.InsertPaymentDetailsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ChitApplication.ServiceReference.InsertPaymentDetailsResponse> ChitApplication.ServiceReference.ChitApplicationServiceSoap.InsertPaymentDetailsAsync(ChitApplication.ServiceReference.InsertPaymentDetailsRequest request) {
            return base.Channel.InsertPaymentDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ChitApplication.ServiceReference.InsertPaymentDetailsResponse> InsertPaymentDetailsAsync(ChitApplication.ServiceReference.Details values) {
            ChitApplication.ServiceReference.InsertPaymentDetailsRequest inValue = new ChitApplication.ServiceReference.InsertPaymentDetailsRequest();
            inValue.Body = new ChitApplication.ServiceReference.InsertPaymentDetailsRequestBody();
            inValue.Body.values = values;
            return ((ChitApplication.ServiceReference.ChitApplicationServiceSoap)(this)).InsertPaymentDetailsAsync(inValue);
        }
    }
}
